config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount ActionCable.server => "/cable"

  root :to => "users#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stripe_webhook

  #rozarpay payments
  resources :rozarpay_payments do
    collection do
      post :unsubscription
      post :success
    end
  end
  resources :order_products do
    collection do
      get :success
      get :stripe_payment
      post :create_card
      get :create_checkout
      get :success
      get :cancel
    end
  end

  #stripe payments
  resources :orders
  resources :stripe_payments do
    collection do
      get :success
      get :cancel
      get :refund_payment
      post :subscription
      post :unsubscription
    end
  end

  resources :theater_show_movie
  resources :movieglu

  resources :users
  get 'notifications/index'
  get 'notifications/:id' => "notifications#show", as:"notification"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  resources :line_items
  delete 'line_items/:id' => "line_items#destroy"
  get 'carts/:id' => "carts#show", as: "cart"
  get 'carts/show_cart' => "carts#show_cart", as: "show_cart"
  delete 'carts/:id' => "carts#destroy"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  include ActiveAdminRole::CanCan::Ability

  def initialize(user)
    user ||= AdminUser.new

    if user.super_user?
      can :manage, :all
    else
      register_role_based_abilities(user)
    end

    # NOTE: Everyone can read the page of Permission Deny
    can :read, ActiveAdmin::Page, name: "Dashboard"
    can :read, ActiveAdmin::Page, name: "AboutUs"
    # can :read, ProductSize
    # can :read, Category
    can :read, Product
    can :read, Order
    can :read, Plan
    can :read, Subscription
    can :read, Charge
    can :read, Notification

    can :read, Item
    can :read, RozarpayPlan
    can :read, RozarpaySubscription
    can :manage, Conversation
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  role_based_authorizable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :notifications, as: :recipient, dependent: :destroy

  has_many :subscriptions
  has_many :charges
  has_many :order_products
  has_many :products, through: :order_products
  has_one :cart, dependent: :destroy
  has_one_attached :image

  #order
  has_many :orders, dependent: :destroy

  #conversation
  has_many :conversations, class_name: "Conversation", foreign_key: "admin_user_id", dependent: :destroy
  has_many :friend_conversations, class_name: "Conversation", foreign_key: "friend_id", dependent: :destroy
  has_many :messages, class_name: "Message", dependent: :destroy

  has_many :rozarpay_subscriptions

  # after_update do
  #   begin
  #     UserMailer.with(user: self, password: self.password).welcome_email.deliver
  #   rescue StandardError => e
  #    puts e
  #   end
  # end

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end

  after_create do
    unless self.admin?
      customer = Razorpay::Customer.create({
        "email": self.email,
      }) || ""

      stripe_customer = Stripe::Customer.create({
        "email": self.email,
      }) || ""

      self.customer_stripe_id = stripe_customer.id
      self.customer_id = customer.id
      self.save
      begin
        UserMailer.with(user: self, password: self.password).welcome_email.deliver
      rescue StandardError => e
       puts e
      end
    end
  end
end

app/models/card_detail.rb
class CardDetail < ApplicationRecord

	after_initialize :create_card

	def create_card
		if self.card_number.present?
			exp = expiry.split('/')
			exp_month = exp[0]
			exp_year = exp[1]
			token = Stripe::Token.create({
	      card: {
	        number: card_number,
	        exp_month: exp_month,
	        exp_year: exp_year,
	        cvc: cvv,
	      },
	    })

	    if token.present?
	    	self.update(card_token: token.id)
	    end
	  end
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  belongs_to :admin_user

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/charge.rb
class Charge < ApplicationRecord
	belongs_to :admin_user
	enum status: {complete: 0, refunded: 1}
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # belongs_to :user
  has_many :messages, dependent: :destroy
  belongs_to :admin_user
end

app/models/item.rb
class Item < ApplicationRecord
	after_create do
		item = Razorpay::Item.create({
		  name: self.name,
		  description: self&.description,
		  amount: self.amount,
		  currency:"INR"
		});

		self.item_id = item.id
		self.save
	end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :admin_user

  def time
  end

  # after_create do
  #   debugger
  #   ActionCable.server.broadcast "chats_channel", self.conversation, self
  #   # ChatsChannel.broadcast_to(self.conversation, self)
  # end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:pending, :paid, :delivered]
  enum payment_mode: [:cash_on_delivery, :online_payment]
  

  belongs_to :product
  belongs_to :admin_user

  has_many :shipments

end

app/models/plan.rb
class Plan < ApplicationRecord
	enum duration: [:day, :week, :month, :year]
	has_one_attached :image

	# scope :created_at_gteq, ->  (data){
  #   self.where('id = ?', data)
  # }
  
  # scope :created_at_lteq_datetime, -> {
  #   self.where('created_at <= ?', Time.now.end_of_day)
  # }

  def self.ransackable_scopes(auth_object = nil)
    [:created_at_gteq_datetime]
  end

	after_create do
		plan = Stripe::Price.create(
				product_data:{
					name: self.name,
					type: "service",
				},
				currency: currency,
				unit_amount: set_price(self.price),
				recurring: {
					interval: 'month'
				}
			)

		self.plan_id = plan.id
		self.save
	end

	def currency
    "inr"
  end

  def set_price(price)
  	price * 100
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many_attached :images
	has_many :order_products
	has_many :admin_users, through: :order_products
	belongs_to :category
	has_many :product_colors, :inverse_of => :product
	has_many :product_sizings

	has_many :orders, dependent: :destroy

	validates :product_type, presence: true

	accepts_nested_attributes_for :product_colors, allow_destroy: true
	accepts_nested_attributes_for :product_sizings, allow_destroy: true

	PRODUCT_TYPE = [
		"Cloths",
		"Electronics",
		"Grocery", 
		"Shoes"	
	]
end

app/models/product_size.rb
class ProductSize < ApplicationRecord

end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
  enum status: [:ordered, :shipment, :out_for_delivery, :arriving]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :admin_user
end

app/models/theater_show.rb
class TheaterShowMovie
  attr_accessor :rating
  
  def intialize(rating)
    @rating = rating
  end

  def show
    data = ""
    (0..9).each do |i|
      if i <= rating.to_i
        data  = data + "<i class='fa fa-star rating-color'></i>"
      else
        data  = data + "<i class='fa fa-star'></i>"
      end
    end
    data
  end
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, uniqueness: true, presence: true
	validates :password, presence: true
	enum status: [:pending, :accepted, :rejected]
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/conversations/_conversation.html.erb
<body>
  <div class="container">
    <div class="row">
      <!-- <nav class="menu">
        <ul class="items">
          <li class="item">
            <i class="fa fa-home" aria-hidden="true"></i>
          </li>
          <li class="item">
            <i class="fa fa-user" aria-hidden="true"></i>
          </li>
          <li class="item">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </li>
          <li class="item item-active">
            <i class="fa fa-commenting" aria-hidden="true"></i>
          </li>
          <li class="item">
            <i class="fa fa-file" aria-hidden="true"></i>
          </li>
          <li class="item">
            <i class="fa fa-cog" aria-hidden="true"></i>
          </li>
        </ul>
      </nav> -->

      <section class="discussions">
        <div class="discussion search">
          <div class="searchbar">
            <i class="fa fa-search" aria-hidden="true"></i>
            <input type="text" placeholder="Search..."></input>
          </div>
        </div>
        <% @conversations.each_with_index do |conversation, index|%>
          <%= link_to admin_conversations_path(convertion_id: conversation.id), style:"text-decoration: none;" do %>
            <div class="discussion  <%= @conversation.id.eql?(conversation.id) ? "message-active" : ""%>">
              <div class="photo" style="background-image: url(<%= get_friend_user(conversation, current_admin_user.id).image.service_url%>);">
                <!-- <div class="online" id="<%= current_admin_user %>"> -->
                  <%= online_status get_friend_user(conversation, current_admin_user.id) %>
                <!-- </div> -->
              </div>
              <div class="desc-contact">
                <p class="name"><%= get_friend_user(conversation, current_admin_user.id).email %></p>
                <p class="message" id="mess_<%= conversation.id%>"><%= last_message(conversation)%></p>
              </div>
              <div class="timer" id="time_<%= conversation.id%>"><%= message_time(conversation)%></div>
            </div>
          <%end%>
        <%end%>
      </section>
      <section class="chat">
        <%= render "conversation_message", conversation: @conversation%>
      </section>
    </div>
  </div>
</body>

<style type="text/css">
  .pagination_information{
    display: none;
  }
</style>

app/views/admin/conversations/_conversation_message.html.erb
<div class="header-chat">
  <i class="icon fa fa-user-o" aria-hidden="true"></i>
  <p class="name">
    <%= get_friend_user(conversation, current_admin_user.id).email%>
  </p>
  <i class="icon clickable fa fa-ellipsis-h right" aria-hidden="true"></i>
  <div style="margin: 5px 20px;">
    <% status = online_status get_friend_user(conversation, current_admin_user.id) %>
    <%= status.split("online_status").second.split("\"></div>").first.strip %>
  </div>
</div>
<div class="messages-chat" id="<%= conversation.id%>">
  <% conversation.messages.group_by { |mess| mess.created_at.strftime("%d %B %Y") }.each do |date, con_message| %>
    <center><p class="top-chat-time"><%= date.eql?(Time.now.strftime("%d %B %Y")) ? "Today" : date %></p></center>
    <%con_message.each do |message|%>
      <% if !message.admin_user_id.eql?(current_admin_user.id)%>
        <div class="message" id="message_<%= message.id %>">
          <div class="photo" style="background-image: url(<%= get_friend_user(conversation, current_admin_user.id).image.service_url%>);">
            <!-- <div class="online"></div> -->
            <%= online_status get_friend_user(conversation, current_admin_user.id) %>
          </div>
          <p class="text"><%= message.body%> </p>
        </div>
        <p class="time"><%= message.created_at.strftime("%Hh%M")%></p>
      <%else%>
        <div class="message text-only" id="message_<%= message.id %>">
          <div class="response">
            <p class="text"> <%= message.body%></p>
          </div>
        </div>
        <p class="response-time time"><%= message.created_at.strftime("%Hh%M")%></p>
      <%end%>
    <%end%>
  <%end%>
</div>
<div class="footer-chat">
  <%= form_tag "/admin/conversations/create_message", method: :post, remote: true do%>
    <i class="icon fa fa-smile-o clickable" style="font-size:25pt;" aria-hidden="true"></i>
    <%= hidden_field_tag :receiver_id, conversation.friend_id%>
    <%= hidden_field_tag :conversation_id, conversation.id%>
    <%= hidden_field_tag :receiver_image, current_admin_user.image.service_url%>
    <p class="emoji-picker-container">
    <%= text_field_tag :body,"",class:"write-message emoji-picker-container", placeholder:"Type your message here", data: { emojiable: true }, required: 'required'%>
    </p>
    <%= submit_tag "Send", class:"icon send fa fa-paper-plane-o clickable"%>
    <!-- <i class="icon send fa fa-paper-plane-o clickable" aria-hidden="true">Send</i> -->
  <%end%>
</div>

<script type="text/javascript">
  $(".send").click(function(){
   $(".write-message").text("")
  })
</script>

app/views/admin/plans/_my_custom_filter.html.erb
<%= text_field_tag 'q[my_custom_filter_cont]', params[:q][:my_custom_filter_cont] %>

app/views/admin/plans/_stripe_plans.html.erb
<!-- <div class="container">
	<%# @plans.each do |plan|%>
		<div class="card border-0" style="width: 18rem;">
			<div class="card-header">
		    <h5 class="card-title"><%#= plan.name%></h5>
		  </div>
		  <img class="card-img-top" src="<%#= @post.image.url if @post.image.present?%>" alt="Card image cap">
		  <div class="card-body">
		    <p class="card-text"><strong>Author: </strong><%#= plan.plan_id%></p>
		    <p class="card-text"><strong>Body: </strong><%#= plan.duration%></p>
		    <p class="card-text"><strong>Tags: </strong><%#= plan.price%></p>
		    <p class="card-text"><strong>Published: </strong><%#= plan.description%></p>
		    <%#= link_to "Subscribe Now", subscription_stripe_payments_path(id:plan.id), method: :post, class:"subscribe mt-5"  unless current_admin_user.admin? %>
		  </div>
		</div>
	<%#end%>
</div> -->

app/views/admin/products/_category.html.erb
<div class="container">
  <%@products.each do |product|%>
    <%= link_to new_order_path(product_id: product.id) do%>
    <div class="card">
      <div class="card__header">
        <img src="<%= product.images.first.service_url%>" alt="card__image" class="card__image" width="600">
      </div>
      <div class="card__body">
        <h4><%= product.name%></h4>
        <p class="description"><%= product.description%></p>
        <p class="product_rating">
          <span class="ratings">4.3<i class="fa fa-star"></i></span>
          <span class="product_stock">(<%= product.stock%>)</span>
          <span class="tag tag-blue"><%= product.product_type%></span>
        </p>
        <p class="product_discount">
          <%if product.discount.present?%>
            <span class="main_price">
              ₹<%= product.price - (product.price * product.discount / 100)%>
            </span>
            <span class="discount_price">₹<%= product.price%></span>
            <span style="color: green;"><%= product.discount%>% off</span><br>
            <small>Free delivery by <span style="font-weight: 600;">Today</span></small>
          <%else%>
            <span class="main_price">₹ <%= product.price%></span><br>
            <small>Free delivery</small>
          <%end%>
        </p>
      </div>
    </div>
    <%end%>
  <%end%>
</div>
<style type="text/css">
  @import url("https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap");

.container {
/*  display: flex;*/
/*  flex-wrap: wrap;*/
/*  justify-content: center;
  max-width: 1200px;
  margin-block: 2rem;*/
  gap: 2rem;
}

img {
  max-width: 100%;
  display: block;
  object-fit: cover;
  height: 150px;
}

.eX72wL{
  position: absolute;
  left: 295px;
}

.card {
  /*display: flex;
  flex-direction: column;*/
  margin-left: 27px;
  display: inline-block;
  margin-top: 12px;
  width: 22%;
  height: 25%;
  overflow: hidden;
  box-shadow: 0 .1rem 1rem rgba(0, 0, 0, 0.1);
  border-radius: 1em;
  background: #ECE9E6;
  background: linear-gradient(to right, #FFFFFF, #ECE9E6);

}

.card__header{
  padding: 10px;
  float: left;
  display: inline;
  width: 45%;
}

.card__body {
  /*padding: 1rem;
  display: flex;
  flex-direction: column;
  gap: .5rem;*/
  padding: 20px 2px;
  float: right;
  display: inline;
  width: 54%;
}


.tag {
  align-self: flex-start;
  padding: .25em .35em;
  border-radius: 1em;
  font-size: .75rem;
  font-weight: 600;
}

.tag + .tag {
  margin-left: .5em;
}

.tag-blue {
  background: #56CCF2;
background: linear-gradient(to bottom, #2F80ED, #56CCF2);
  color: #fafafa;
}

.tag-brown {
  background: #D1913C;
background: linear-gradient(to bottom, #FFD194, #D1913C);
  color: #fafafa;
}

.tag-red {
  background: #cb2d3e;
background: linear-gradient(to bottom, #ef473a, #cb2d3e);
  color: #fafafa;
}

.card__body h4 {
  font-size: 1.0rem;
  text-transform: capitalize;
  font-weight: 600;
}

.user {
  display: flex;
  gap: .5rem;
}

.user__image {
  border-radius: 50%;
}

.user__info > small {
  color: #666;
}

.discount_price{
  padding-right: 2px;
  text-decoration: line-through;
  color: gray;
}

.main_price{
  margin-top: 5px;
  padding-right: 2px;
  font-weight: 600;
}

.description{
  margin: 7px 0px;
  color: gray;
  font-size: 12px;
  line-height: 1;
}

.ratings{
  line-height: normal;
  display: inline-block;
  color: #fff;
  padding: 2px 4px 2px 6px;
  border-radius: 3px;
  font-weight: 500;
  font-size: 12px;
  vertical-align: middle;
  background-color: #388e3c;
}

.product_stock{
/*  padding: 0px 2px;*/
  color: gray;
}

.fa-star:before {
    content: "\f005";
    font-size: 10px;
    padding: 0px 2px;
}
p{
  margin: 0;
}
.product_rating{
    padding: 4px 0px;
  }

@media only screen and (max-width: 1048px){
.card {
    margin-left: 17px;
  }

  .product_rating,.ratings, .tag, .fa-star{
    font-size: 9px;
  }
  .description,.product_discount{
    font-size: 11px;
  }
}
</style>

app/views/admin/products/get_product_size.html.erb
<select name="product[product_sizings_attributes][0][product_size_id]" id="product_product_sizings_attributes_0_product_size_id" data-tags="false">
<% @product_size.each do |size, value|%>
  <option value="<%= size %>"><%= value %></option>
<%end%>
</select>