config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount ActionCable.server => "/cable"

  root :to => "users#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stripe_webhook

  #rozarpay payments
  resources :rozarpay_payments do
    collection do
      post :unsubscription
      post :success
    end
  end
  resources :order_products do
    collection do
      get :success
      get :stripe_payment
      post :create_card
      get :create_checkout
      get :success
      get :cancel
    end
  end

  #stripe payments
  resources :orders
  resources :stripe_payments do
    collection do
      get :success
      get :cancel
      get :refund_payment
      post :subscription
      post :unsubscription
    end
  end

  resources :theater_show_movie
  resources :movieglu

  resources :users
  get 'notifications/index'
  get 'notifications/:id' => "notifications#show", as:"notification"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  resources :line_items
  delete 'line_items/:id' => "line_items#destroy"
  get 'carts/:id' => "carts#show", as: "cart"
  get 'carts/show_cart' => "carts#show_cart", as: "show_cart"
  delete 'carts/:id' => "carts#destroy"

end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/controllers/notifications_controller.rb
require "rqrcode"
class NotificationsController < ApplicationController
  def index
    @notifications = current_admin_user.notifications.order(created_at: :desc)
    render layout: false
  end

  def show
    @notification = Notification.find_by(id: params[:id])
    @notification.update(read_at: DateTime.now)
    qrcode = RQRCode::QRCode.new("
      Title: #{@notification.params[:message]},
      Plan / Product: #{@notification&.params[:params].present? ? @notification&.params[:params][0][:name] : nil},
      Amount: #{@notification&.params[:params].present? ? @notification&.params[:params][0][:price] : 0},
      Status: Paid
      ")
    @png = qrcode.as_png(
          bit_depth: 1,
          border_modules: 4,
          color_mode: ChunkyPNG::COLOR_GRAYSCALE,
          color: "black",
          file: nil,
          fill: "white",
          module_px_size: 10,
          resize_exactly_to: false,
          resize_gte_to: false,
          size: 200
        ).to_data_url
    if params[:format].present?
      respond_to do |format|
        format.html
        format.pdf do
            render pdf: "Invoice No. #{@notification.id}",
            page_size: 'A4',
            template: "notifications/show.html.erb",
            layout: "pdf.html",
            orientation: "Landscape",
            lowquality: true,
            zoom: 1,
            dpi: 75
        end
      end
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<h1>Notifications</h1>

app/views/notifications/index.html.erb
<div class="notification-header">
  <h1 style="display: inline-block; font-weight: 600;">Notifications</h1>
  <button type="button" class="close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<main>
  <div class="notification-container">
    <% @notifications.each do |notification| %>
      <% instance = notification.to_notification %>
        <p class="notification_new <% notification.read_at.present? ? 'read' : 'unread' %>"> 
          <span class="notification-left"><%= notification.params[:message] %>
          </span>
          <span class="notification-right">
            <span style="float: right;">
              <small><i><%= notification_time(notification)%></i></small>
              <button onclick="location.href='/notifications/<%= notification.id %>'" type="button" class="notification-view">view</button>
            </span>
          </span>
        </p> 
    <% end %>
  </div>
</main>

<script>
  $(".close").click( function(){
    $(".notification-list").addClass('hide')
    location.reload(true)
  });
</script>


<style type="text/css">
  main{
    padding: 0px 10px;
  }
  .close{
    padding: 0;
    border: none;
    background: none;
    font-size: 35px;
    margin-left: 205px;
    cursor: pointer;
  }

  small{
    opacity: 0.7;
  }

  .notification-view{
    color: white;
    font-weight: 600;
    border: 2px solid;
    border-radius: 5px;
    background: #1398f5;
  }

  .read{
    background: #919fa59e;
  }

  .unread{
    background: #1398f5;
  }
  .notification_new{
    background: #bbdbe7 !important;
    padding: 2px 10px !important;
    height: auto !important;
    overflow: hidden;
    border-radius: 2px !important;
  }

  .notification-left{
    word-wrap: break-word;
    width: 63%;
    float: left;
  }

  .notification-right{
    /*width: 37%;
    float: right;*/
  }

  .notification-list::-webkit-scrollbar {
    width: 0.8em;
  }
   
  .notification-list::-webkit-scrollbar-track {
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
   
  .notification-list::-webkit-scrollbar-thumb {
    background-color: darkgrey;
    outline: 0px solid slategrey;
  }
</style>

app/views/notifications/show.html.erb
<div class="container"> 
  <div class="row m-0"> 
    <div class="col-md-12 col-12"> 
      <div class="row"> 
        <div class="col-12 mb-4"> 
          <div class="row box-right"> 
            <div class="col-md-8 ps-0 "> 
              <p class="ps-3 textmuted fw-bold h6 mb-4">
                <%= link_to 'DOWNLOAD PDF', notification_path(@notification, format: :pdf) %>
              </p>
              <p class="ps-3 textmuted fw-bold h6 mb-0">TOTAL AMOUNT</p> 
              <p class="h1 fw-bold d-flex"> 
                <span class=" fas fa-dollar-sign textmuted pe-1 h6 align-text-top mt-1">
                </span>
                <%= @notification&.params[:params].present? ? @notification&.params[:params][0][:price] : 0 %> 
              </p>
              </div> <div class="col-md-4"> 
                <p class="p-blue" style="text-align: center;"> 
                  <!-- <span class="fas fa-circle pe-2"></span> -->
                  Scan QR for Details.
                </p> 
                  <p class="fw-bold mb-3">

                    <img src= <%= @png.to_s %> alt="Red dot" style="width: 170px;height: 170px;"/>
                  </p>  
                </div> 
              </div> 
            </div>
            <div class="col-12 px-0"> 
              <div class="box-right"> 
                <div class="d-flex mb-2"> 
                  <p class="fw-bold"><%= @notification.params[:message]%></p> 
                  <p class="ms-auto textmuted">
                    <span class="fas fa-times"></span>
                  </p> 
                </div> 
                <div class="d-flex mb-2">
                  <!-- <p class="ms-auto bg btn btn-primary p-blue h8">
                    <span class="far fa-clone pe-2"></span>COPY PAYMENT LINK 
                  </p>  -->
                </div> 
                <div class="row"> 
                  <div class="col-12 mb-2"> 
                    <p class="textmuted h8">Plan / Product</p> 
                    <p class="mb-2"><%= @notification&.params[:params].present? ? @notification&.params[:params][0][:name] : nil %></p> 
                  </div> 
                  <div class="col-6"> 
                    <p class="textmuted h8">Payment Date</p> 
                    <p class="mb-3">
                      <%= @notification&.params[:params].present? ? @notification&.params[:params][0][:created_at].strftime("%B %d, %y") : nil %>
                    </p> 
                  </div> 
                  <div class="col-6"> 
                    <p class="textmuted h8">Due on</p> 
                    <p class="mb-3">Oct 25, 2020</p> 
                  </div> 
                </div> 
              </div> 
            </div> 
          </div> 
        </div> 
      </div>
    </div> 
  </div> 
</div>
<style type="text/css">
p {
    margin: 0
}

.container {
    max-width: 700px;
    margin: 30px auto;
    background-color: #e8eaf6;
    padding: 35px !important;
    height: 500px !important;
    border-radius: 18px;
}

.box-right {
    padding: 22px 25px 0px 25px;
    background-color: white;
    border-radius: 15px
}

.box-left {
    padding: 20px 20px;
    background-color: white;
    border-radius: 15px
}

.textmuted {
    color: #7a7a7a
}

.bg-green {
    background-color: #d4f8f2;
    color: #06e67a;
    padding: 3px 0;
    display: inline;
    border-radius: 25px;
    font-size: 11px
}

.p-blue {
    font-size: 14px;
    color: #1976d2
}

.fas.fa-circle {
    font-size: 12px
}

.p-org {
    font-size: 14px;
    color: #fbc02d
}

.h7 {
    font-size: 15px
}

.h8 {
    font-size: 12px
}

.h9 {
    font-size: 10px
}

.bg-blue {
    background-color: #dfe9fc9c;
    border-radius: 5px
}

.form-control {
    box-shadow: none !important
}

.card input::placeholder {
    font-size: 14px
}

::placeholder {
    font-size: 14px
}

input.card {
    position: relative
}

.far.fa-credit-card {
    position: absolute;
    top: 10px;
    padding: 0 15px
}

.fas,
.far {
    cursor: pointer
}

.cursor {
    cursor: pointer
}

.btn.btn-primary {
    box-shadow: none;
    height: 40px;
    padding: 11px
}

.bg.btn.btn-primary {
    background-color: transparent;
    border: none;
    color: #1976d2
}

.bg.btn.btn-primary:hover {
    color: #539ee9
}

.fw-bold {
    padding: 0px !important;
}

@media(max-width:320px) {
    .h8 {
        font-size: 11px
    }

    .h7 {
        font-size: 13px
    }

    ::placeholder {
        font-size: 10px
    }
}


</style>