config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount ActionCable.server => "/cable"

  root :to => "users#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stripe_webhook

  #rozarpay payments
  resources :rozarpay_payments do
    collection do
      post :unsubscription
      post :success
    end
  end
  resources :order_products do
    collection do
      get :success
      get :stripe_payment
      post :create_card
      get :create_checkout
      get :success
      get :cancel
    end
  end

  #stripe payments
  resources :orders
  resources :stripe_payments do
    collection do
      get :success
      get :cancel
      get :refund_payment
      post :subscription
      post :unsubscription
    end
  end

  resources :theater_show_movie
  resources :movieglu

  resources :users
  get 'notifications/index'
  get 'notifications/:id' => "notifications#show", as:"notification"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  resources :line_items
  delete 'line_items/:id' => "line_items#destroy"
  get 'carts/:id' => "carts#show", as: "cart"
  get 'carts/show_cart' => "carts#show_cart", as: "show_cart"
  delete 'carts/:id' => "carts#destroy"

end

app/models/user.rb
class User < ApplicationRecord
	validates :email, uniqueness: true, presence: true
	validates :password, presence: true
	enum status: [:pending, :accepted, :rejected]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			@user.update(status:"pending")
			redirect_to root_path, notice:"Application submitted and please wait for admin response on email."
		else
			render :index
		end
	end

	private

	def user_params
		params.permit(:email, :password, :first_name, :last_name)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
  <a class="navbar-brand text-dark" href="#">Demo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
		<%= link_to "Dashboard", admin_user_session_path(), class:"nav-link"%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<% if @user.errors.any? %>
  <div id="error_explanation" class="pl-5 pt-2">
    <h5><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h5>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Responsive Registration Form</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <%= form_for @user do |f| %>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <%= f.text_field :email, name:"email", placeholder:"Email" %>
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
            <%= f.text_field :password, name:"password", placeholder:"Password" %>
          </div>
          <!-- div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
            <%#= f.text_field :password, name:"password", placeholder:"Re-type Password" %>
          </div> -->
          <div class="row clearfix">
            <div class="col_half">
              <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                <%= f.text_field :first_name, name:"first_name", placeholder:"First Name" %>
              </div>
            </div>
            <div class="col_half">
              <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                <%= f.text_field :last_name, name:"last_name", placeholder:"Last Name" %>
              </div>
            </div>
          </div>
          <%= f.submit "Register", class:"button", type:"submit", value:"Register" %>
        <%end%>
      </div>
    </div>
  </div>
</div>