config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount ActionCable.server => "/cable"

  root :to => "users#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :stripe_webhook

  #rozarpay payments
  resources :rozarpay_payments do
    collection do
      post :unsubscription
      post :success
    end
  end
  resources :order_products do
    collection do
      get :success
      get :stripe_payment
      post :create_card
      get :create_checkout
      get :success
      get :cancel
    end
  end

  #stripe payments
  resources :orders
  resources :stripe_payments do
    collection do
      get :success
      get :cancel
      get :refund_payment
      post :subscription
      post :unsubscription
    end
  end

  resources :theater_show_movie
  resources :movieglu

  resources :users
  get 'notifications/index'
  get 'notifications/:id' => "notifications#show", as:"notification"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  resources :line_items
  delete 'line_items/:id' => "line_items#destroy"
  get 'carts/:id' => "carts#show", as: "cart"
  get 'carts/show_cart' => "carts#show_cart", as: "show_cart"
  delete 'carts/:id' => "carts#destroy"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  include ActiveAdminRole::CanCan::Ability

  def initialize(user)
    user ||= AdminUser.new

    if user.super_user?
      can :manage, :all
    else
      register_role_based_abilities(user)
    end

    # NOTE: Everyone can read the page of Permission Deny
    can :read, ActiveAdmin::Page, name: "Dashboard"
    can :read, ActiveAdmin::Page, name: "AboutUs"
    # can :read, ProductSize
    # can :read, Category
    can :read, Product
    can :read, Order
    can :read, Plan
    can :read, Subscription
    can :read, Charge
    can :read, Notification

    can :read, Item
    can :read, RozarpayPlan
    can :read, RozarpaySubscription
    can :manage, Conversation
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  role_based_authorizable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :notifications, as: :recipient, dependent: :destroy

  has_many :subscriptions
  has_many :charges
  has_many :order_products
  has_many :products, through: :order_products
  has_one :cart, dependent: :destroy
  has_one_attached :image

  #order
  has_many :orders, dependent: :destroy

  #conversation
  has_many :conversations, class_name: "Conversation", foreign_key: "admin_user_id", dependent: :destroy
  has_many :friend_conversations, class_name: "Conversation", foreign_key: "friend_id", dependent: :destroy
  has_many :messages, class_name: "Message", dependent: :destroy

  has_many :rozarpay_subscriptions

  # after_update do
  #   begin
  #     UserMailer.with(user: self, password: self.password).welcome_email.deliver
  #   rescue StandardError => e
  #    puts e
  #   end
  # end

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end

  after_create do
    unless self.admin?
      customer = Razorpay::Customer.create({
        "email": self.email,
      }) || ""

      stripe_customer = Stripe::Customer.create({
        "email": self.email,
      }) || ""

      self.customer_stripe_id = stripe_customer.id
      self.customer_id = customer.id
      self.save
      begin
        UserMailer.with(user: self, password: self.password).welcome_email.deliver
      rescue StandardError => e
       puts e
      end
    end
  end
end

app/models/card_detail.rb
class CardDetail < ApplicationRecord

	after_initialize :create_card

	def create_card
		if self.card_number.present?
			exp = expiry.split('/')
			exp_month = exp[0]
			exp_year = exp[1]
			token = Stripe::Token.create({
	      card: {
	        number: card_number,
	        exp_month: exp_month,
	        exp_year: exp_year,
	        cvc: cvv,
	      },
	    })

	    if token.present?
	    	self.update(card_token: token.id)
	    end
	  end
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  belongs_to :admin_user

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/charge.rb
class Charge < ApplicationRecord
	belongs_to :admin_user
	enum status: {complete: 0, refunded: 1}
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # belongs_to :user
  has_many :messages, dependent: :destroy
  belongs_to :admin_user
end

app/models/item.rb
class Item < ApplicationRecord
	after_create do
		item = Razorpay::Item.create({
		  name: self.name,
		  description: self&.description,
		  amount: self.amount,
		  currency:"INR"
		});

		self.item_id = item.id
		self.save
	end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :admin_user

  def time
  end

  # after_create do
  #   debugger
  #   ActionCable.server.broadcast "chats_channel", self.conversation, self
  #   # ChatsChannel.broadcast_to(self.conversation, self)
  # end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:pending, :paid, :delivered]
  enum payment_mode: [:cash_on_delivery, :online_payment]
  

  belongs_to :product
  belongs_to :admin_user

  has_many :shipments

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :admin_user
  belongs_to :product
end

app/models/plan.rb
class Plan < ApplicationRecord
	enum duration: [:day, :week, :month, :year]
	has_one_attached :image

	# scope :created_at_gteq, ->  (data){
  #   self.where('id = ?', data)
  # }
  
  # scope :created_at_lteq_datetime, -> {
  #   self.where('created_at <= ?', Time.now.end_of_day)
  # }

  def self.ransackable_scopes(auth_object = nil)
    [:created_at_gteq_datetime]
  end

	after_create do
		plan = Stripe::Price.create(
				product_data:{
					name: self.name,
					type: "service",
				},
				currency: currency,
				unit_amount: set_price(self.price),
				recurring: {
					interval: 'month'
				}
			)

		self.plan_id = plan.id
		self.save
	end

	def currency
    "inr"
  end

  def set_price(price)
  	price * 100
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many_attached :images
	has_many :order_products
	has_many :admin_users, through: :order_products
	belongs_to :category
	has_many :product_colors, :inverse_of => :product
	has_many :product_sizings

	has_many :orders, dependent: :destroy

	validates :product_type, presence: true

	accepts_nested_attributes_for :product_colors, allow_destroy: true
	accepts_nested_attributes_for :product_sizings, allow_destroy: true

	PRODUCT_TYPE = [
		"Cloths",
		"Electronics",
		"Grocery", 
		"Shoes"	
	]
end

app/models/product_size.rb
class ProductSize < ApplicationRecord

end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
  enum status: [:ordered, :shipment, :out_for_delivery, :arriving]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :admin_user
end

app/models/theater_show.rb
class TheaterShowMovie
  attr_accessor :rating
  
  def intialize(rating)
    @rating = rating
  end

  def show
    data = ""
    (0..9).each do |i|
      if i <= rating.to_i
        data  = data + "<i class='fa fa-star rating-color'></i>"
      else
        data  = data + "<i class='fa fa-star'></i>"
      end
    end
    data
  end
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, uniqueness: true, presence: true
	validates :password, presence: true
	enum status: [:pending, :accepted, :rejected]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :current_cart
  
  def show_cart
    redirect_to cart_path(@current_cart)
  end

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to admin_products_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="card-show">
  <span class="svg_icon">
    <%= link_to admin_products_path do%>
      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg>
    <%end%>
  </span>
  <h2 class="card-show-child">Cart show</h2>
  <%= button_to "Empty cart(#{@cart.line_items.count})", cart_path(@current_cart),
  method: :delete, data: {confirm: "Are you sure?"}, class:"card-show-child" %>
  <h5 class="card-show-child">Sub total: <%= number_to_currency(@cart.sub_total, unit: "₹") %></h5>
</div>

<%unless @cart.line_items.present?%>
  <div class="text-center p-2" style="background: #009688;">
    <p class="fw-bold text-light">You are not added product on cart!</p>
  </div>
<%end%>

<div class="row">
  <% @cart.line_items.each do |line_item| %>
  <div class="column">
    <div class="card-parent">
        <div class="card-child">
          <%= image_tag(line_item.product.images.first) if line_item.product.images.attached?%><br>
        </div>
        <div class="card-child">
          Item: <%= line_item.product.name %><br>
          Price: <%= number_to_currency(line_item.product.price, unit: "₹") %><br>
          Quantity: <%= line_item.quantity %><br>
          Total Price: <%= number_to_currency(line_item.total_price, unit: "₹") %>
        </div>
        <div class="card-child trash-button">
            <%= button_to line_item_path(line_item), method: :delete do %>
              <i class="fa fa-trash fa-common"></i>
            <%end%>
          </div>
        <div class="card-child-action">
          <div class="cart-action">
            <%= button_to line_item_add_path(:id => line_item), method: :post, class:"plus" do %>
               <i class="fa fa-plus fa-common"></i>
            <%end%>
          </div>
          <div class="cart-action item-quantity">
            <%= line_item.quantity %>
          </div>
          <div class="cart-action">
            <%= button_to line_item_reduce_path(:id => line_item), method: :post, class:"minus" do %>
              <i class="fa fa-minus fa-common"></i>
            <%end%>
          </div>
          <div class="cart-action">
            <%= button_to stripe_payments_path(product_id: line_item.product.id, quantity: line_item.quantity), method: :post, class: "paypal" do %>
              <i class="fa fa-paypal fa-common"></i>
            <%end%>
          </div>
        </div>
    </div>
  </div>
  <% end %>
</div>